name: Hello World Example

on:
  push:
    branches: [ main ]           # ← optionnel : limite aux push sur main
  workflow_dispatch:             # ← permet de lancer manuellement depuis l'interface

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "hello world"
        


# name: Hello World

# on: [push, workflow_dispatch]

# jobs:
#   hello:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "hello world"