name: Exercice Merge message

on:
  workflow_dispatch:
  pull_request:
    types: [closed]

jobs:
  say-merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "ðŸŽ‰ PR (pull request) #${{ github.event.pull_request.number }} mergÃ©e ! Merci @${{ github.event.pull_request.user.login }}"